version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/basic_app/
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: run.sh
      timeout: 300
      runas: root
